In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Libraries imported successfully!
Pandas version: 2.3.3
NumPy version: 2.3.5

In [3]:
df = pd.read_csv('student_scores.csv')

print("Dataset loaded successfully!")
print(f"\nDataset shape: {df.shape}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print("\nFirst few rows of the dataset:")
df.head()

Dataset loaded successfully!

Dataset shape: (10, 7)
Number of rows: 10
Number of columns: 7

First few rows of the dataset:

   Student_ID    Name  Age Gender  Math_Score  Science_Score  English_Score
0           1     Ali   16      M        85.0           78.0           88.0
1           2    Sara   17      F        90.0            NaN           82.0
2           3   Ahmed   16      M        76.0           74.0           80.0
3           4  Ayesha   15      F         NaN           85.0           79.0
4           5   Bilal   17      M        88.0           90.0           85.0

In [4]:
print("Dataset Information:")
print("="*50)
df.info()

print("\n" + "="*50)
print("\nColumn Names:")
print(df.columns.tolist())

print("\n" + "="*50)
print("\nBasic Statistics:")
df.describe()

Dataset Information:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     10 non-null     int64
 1   Name           10 non-null     object
 2   Age            10 non-null     int64
 3   Gender         10 non-null     object
 4   Math_Score     9 non-null      float64
 5   Science_Score  9 non-null      float64
 6   English_Score  9 non-null      float64
dtypes: float64(3), int64(2), object(2)
memory usage: 692.0+ bytes

==================================================

Column Names:
['Student_ID', 'Name', 'Age', 'Gender', 'Math_Score', 'Science_Score', 'English_Score']

==================================================

Basic Statistics:

       Student_ID        Age  Math_Score  Science_Score  English_Score
count    10.00000  10.000000    9.000000       9.000000       9.000000
mean      5.50000  16.000000   84.555556      82.555556      83.555556
std       3.02765   0.816497    8.001736       8.889757       6.728876
min       1.00000  15.000000   70.000000      68.000000      72.000000
25%       3.25000  15.250000   80.000000      78.000000      80.000000
50%       5.50000  16.000000   85.000000      83.000000      82.000000
75%       7.75000  16.750000   90.000000      90.000000      88.000000
max      10.00000  17.000000   95.000000      95.000000      94.000000

In [5]:
# Check for missing values in the dataset
print("Missing Values Analysis:")
print("="*50)

missing_values = df.isnull().sum()
print("\nMissing values per column:")
print(missing_values)

print("\n" + "="*50)
missing_percentage = (df.isnull().sum() / len(df)) * 100
print("\nMissing values percentage:")
print(missing_percentage)

print("\n" + "="*50)
print(f"\nTotal missing values in dataset: {df.isnull().sum().sum()}")

Missing Values Analysis:
==================================================

Missing values per column:
Student_ID       0
Name             0
Age              0
Gender           0
Math_Score       1
Science_Score    1
English_Score    1
dtype: int64

==================================================

Missing values percentage:
Student_ID        0.0
Name              0.0
Age               0.0
Gender            0.0
Math_Score       10.0
Science_Score    10.0
English_Score    10.0
dtype: float64

==================================================

Total missing values in dataset: 3

In [6]:
# Clean column names (remove extra spaces, make consistent)
print("Original column names:")
print(df.columns.tolist())

# Strip whitespace and make consistent
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.lower()

print("\n" + "="*50)
print("\nCleaned column names:")
print(df.columns.tolist())
print("\nColumn names cleaned successfully!")

Original column names:
['Student_ID', 'Name', 'Age', 'Gender', 'Math_Score', 'Science_Score', 'English_Score']

==================================================

Cleaned column names:
['student_id', 'name', 'age', 'gender', 'math_score', 'science_score', 'english_score']

Column names cleaned successfully!

In [7]:
# Handle missing values - Fill with column mean for numeric columns
print("Handling missing values...")
print("="*50)

# Store original shape
original_shape = df.shape

# Fill missing numeric values with column mean
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        mean_value = df[col].mean()
        df[col].fillna(mean_value, inplace=True)
        print(f"Filled missing values in '{col}' with mean: {mean_value:.2f}")

print("\n" + "="*50)
print(f"\nOriginal shape: {original_shape}")
print(f"Current shape: {df.shape}")
print(f"\nRemaining missing values: {df.isnull().sum().sum()}")

Handling missing values...
==================================================
Filled missing values in 'math_score' with mean: 84.56
Filled missing values in 'science_score' with mean: 82.56
Filled missing values in 'english_score' with mean: 83.56

==================================================

Original shape: (10, 7)
Current shape: (10, 7)

Remaining missing values: 0

In [8]:
# Check for duplicate records
print("Checking for duplicate records...")
print("="*50)

duplicate_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_count}")

if duplicate_count > 0:
    print("\nDuplicate rows found:")
    print(df[df.duplicated(keep=False)])
else:
    print("\nNo duplicate rows found in the dataset.")

Checking for duplicate records...
==================================================

Number of duplicate rows: 0

No duplicate rows found in the dataset.

In [9]:
# Remove duplicate records if any exist
print("Removing duplicate records...")
print("="*50)

shape_before = df.shape
df.drop_duplicates(inplace=True)
shape_after = df.shape

rows_removed = shape_before[0] - shape_after[0]
print(f"\nShape before removing duplicates: {shape_before}")
print(f"Shape after removing duplicates: {shape_after}")
print(f"Number of duplicate rows removed: {rows_removed}")

# Reset index after removing duplicates
df.reset_index(drop=True, inplace=True)
print("\nIndex reset successfully!")

Removing duplicate records...
==================================================

Shape before removing duplicates: (10, 7)
Shape after removing duplicates: (10, 7)
Number of duplicate rows removed: 0

Index reset successfully!

In [10]:
#  Display cleaned dataset summary
print("CLEANED DATASET SUMMARY")
print("="*50)

print(f"\nFinal shape: {df.shape}")
print(f"Total students: {len(df)}")
print(f"Total missing values: {df.isnull().sum().sum()}")

print("\n" + "="*50)
print("\nCleaned column names:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

print("\n" + "="*50)
print("\nFirst 5 rows of cleaned data:")
df.head()

CLEANED DATASET SUMMARY
==================================================

Final shape: (10, 7)
Total students: 10
Total missing values: 0

==================================================

Cleaned column names:
1. student_id
2. name
3. age
4. gender
5. math_score
6. science_score
7. english_score

==================================================

First 5 rows of cleaned data:

   student_id    name  age gender  math_score  science_score  english_score
0           1     Ali   16      M   85.000000      78.000000           88.0
1           2    Sara   17      F   90.000000      82.555556           82.0
2           3   Ahmed   16      M   76.000000      74.000000           80.0
3           4  Ayesha   15      F   84.555556      85.000000           79.0
4           5   Bilal   17      M   88.000000      90.000000           85.0

In [11]:
# Perform basic statistical analysis
print("BASIC STATISTICAL ANALYSIS")
print("="*50)

print("\nDescriptive Statistics:")
print(df.describe())

print("\n" + "="*50)
print("\nGender Distribution:")
print(df['gender'].value_counts())

print("\n" + "="*50)
print("\nAge Distribution:")
print(df['age'].value_counts().sort_index())

BASIC STATISTICAL ANALYSIS
==================================================

Descriptive Statistics:
       student_id        age  math_score  science_score  english_score
count    10.00000  10.000000   10.000000      10.000000      10.000000
mean      5.50000  16.000000   84.555556      82.555556      83.555556
std       3.02765   0.816497    7.544109       8.381343       6.344046
min       1.00000  15.000000   70.000000      68.000000      72.000000
25%       3.25000  15.250000   81.138889      78.000000      80.250000
50%       5.50000  16.000000   85.000000      82.777778      82.777778
75%       7.75000  16.750000   89.500000      88.750000      87.250000
max      10.00000  17.000000   95.000000      95.000000      94.000000

==================================================

Gender Distribution:
gender
M    5
F    5
Name: count, dtype: int64

==================================================

Age Distribution:
age
15    3
16    4
17    3
Name: count, dtype: int64

In [12]:
# Analyze scores by subject
print("SUBJECT-WISE SCORE ANALYSIS")
print("="*50)

print("\nMath Scores:")
print(f"Mean: {df['math_score'].mean():.2f}")
print(f"Median: {df['math_score'].median():.2f}")
print(f"Min: {df['math_score'].min():.2f}")
print(f"Max: {df['math_score'].max():.2f}")

print("\n" + "-"*50)
print("\nScience Scores:")
print(f"Mean: {df['science_score'].mean():.2f}")
print(f"Median: {df['science_score'].median():.2f}")
print(f"Min: {df['science_score'].min():.2f}")
print(f"Max: {df['science_score'].max():.2f}")

print("\n" + "-"*50)
print("\nEnglish Scores:")
print(f"Mean: {df['english_score'].mean():.2f}")
print(f"Median: {df['english_score'].median():.2f}")
print(f"Min: {df['english_score'].min():.2f}")
print(f"Max: {df['english_score'].max():.2f}")

SUBJECT-WISE SCORE ANALYSIS
==================================================

Math Scores:
Mean: 84.56
Median: 85.00
Min: 70.00
Max: 95.00

--------------------------------------------------

Science Scores:
Mean: 82.56
Median: 82.78
Min: 68.00
Max: 95.00

--------------------------------------------------

English Scores:
Mean: 83.56
Median: 82.78
Min: 72.00
Max: 94.00

In [13]:
# Save the cleaned dataset
output_filename = 'student_scores_cleaned.csv'
df.to_csv(output_filename, index=False)

print("TASK COMPLETED!")
print("="*50)
print(f"\nCleaned dataset saved as: {output_filename}")
print(f"Total records: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print("\nData cleaning and basic analysis completed successfully!")

TASK COMPLETED!
==================================================

Cleaned dataset saved as: student_scores_cleaned.csv
Total records: 10
Total columns: 7

Data cleaning and basic analysis completed successfully!